---
# Define OpenVPN client configs here

- name: install openvpn
  apt:
    name: openvpn
    state: present

# - name: "ensure that {{ node_hostname }}.ovpn file exists on the control node"
#   stat:
#     path: "{{ openvpn_fetch_config_directory }}/{{ openvpn_server_hostname }}/{{ node_hostname }}.ovpn"
#   register: local_ovpn_file
#   delegate_to: localhost

# Notes: .ovpn files are for Windows and .conf files are for Linux
- name: transfer a generated ovpn file from the local machine to the node
  copy:
    src: "{{ openvpn_fetch_config_directory }}/{{ openvpn_server_hostname }}/{{ node_hostname }}.ovpn"
    dest: "{{ openvpn_config_directory }}/client.conf"
    owner: root
    group: root
    mode: 0750
  # when: local_ovpn_file.stat.exists

- block:
    # setup auto auth when openvpn client password is used
    - name: create openvpn client password file
      file:
        path: /etc/openvpn/auth.txt
        owner: root
        group: root
        state: touch
        mode: 0400

    - name: append password to auth.txt
      lineinfile:
        path: /etc/openvpn/auth.txt
        regexp: '^{{ openvpn_client_pass }}'
        line: '{{ openvpn_client_pass }}'
        state: present
        create: true

    - name: append path to password file in client.conf
      lineinfile:
        path: /etc/openvpn/client.conf
        regexp: '^askpass'
        insertafter: '^client'
        line: 'askpass /etc/openvpn/auth.txt'

  when: openvpn_client_pass_auth

- name: enable openvpn autostart
  become: true
  lineinfile:
    path: /etc/default/openvpn
    regexp: '^AUTOSTART='
    line: 'AUTOSTART="all"'
