---
# Ansible playbook for Raspberry Pi nodes

- hosts: server
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - roles/openvpn-server-local

- hosts: node
  become: true
  pre_tasks:

    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_action
      # when: network_connectivity

    # - tasks/ssh-key-exchange.yml
    # - tasks/snmp-exporter-config-generator.yml
    # - tasks/securing-servers.yml

  vars_files:
    - vars/all.yml

  # ansible-galaxy install <galaxy-user.role-name>
  roles:
    - roles/init-local
    - roles/openvpn-client-local
    - roles/prometheus-local
    - roles/snmp-exporter-local
    - roles/node-exporter-local
    - roles/blackbox-exporter-local
    - roles/grafana-local
    - roles/influxdb-local
    - roles/telegraf-local
    # - roles/test-local

  post_tasks:
    # - name: enable and start services
    # manually check issues with services:
    # sudo journalctl -r | grep (service-name) | head -n 50
