---
# Ansible playbook for Raspberry Pi nodes

- hosts: server
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - roles/openvpn_server

- hosts: node
  become: true
  pre_tasks:

    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_action

    - import_tasks: tasks/offline_copy.yml

  vars_files:
    - vars/all.yml

  roles:
    - roles/init
    - roles/openvpn_client
    - roles/prometheus
    - roles/snmp_exporter
    - roles/node_exporter
    - roles/blackbox_exporter
    - roles/grafana
    - roles/influxdb
    - roles/telegraf
    # - roles/test

  post_tasks:
    - import_tasks: tasks/start_services.yml
    # check issues with services in cli:
    # sudo journalctl -r | grep (service-name) | head -n 50
