---
# Ansible playbook for Raspberry Pi nodes

- hosts: server
  become: true
  vars_files:
    - vars/all_node.yml
  roles:
    - roles/openvpn_server_node

- hosts: node
  become: true
  pre_tasks:

    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_action

    - import_tasks: tasks/offline_copy.yml
    # - tasks/snmp_exporter_config_generator.yml

  vars_files:
    - vars/all_node.yml


    - roles/init_node
    - roles/openvpn_client_node
    - roles/prometheus_node
    - roles/snmp_exporter_node
    - roles/node_exporter_node
    - roles/blackbox_exporter_node
    - roles/grafana_node
    - roles/influxdb_node
    - roles/telegraf_node
    # - roles/test_node

  post_tasks:
    - import_tasks: tasks/start_services.yml
    # check issues with services in cli:
    # sudo journalctl -r | grep (service-name) | head -n 50
