---
# Ansible playbook for Raspberry Pi nodes

- hosts: server
  become: true
  vars_files:
    - vars/all_node.yml
  roles:
    - roles/openvpn_server_node

- hosts: node
  become: true
  pre_tasks:

    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_action
      # when: network_connectivity

    # - tasks/ssh-key-exchange.yml
    # - tasks/snmp-exporter-config-generator.yml
    # - tasks/securing-servers.yml

  vars_files:
    - vars/all.yml

  roles:
    - roles/init_node
    - roles/openvpn_client_node
    - roles/prometheus_node
    - roles/snmp_exporter_node
    - roles/node_exporter_node
    - roles/blackbox_exporter_node
    - roles/grafana_node
    - roles/influxdb_node
    - roles/telegraf_node
    # - roles/test_node

  post_tasks:
    # - name: enable and start services
    # manually check issues with services:
    # sudo journalctl -r | grep (service-name) | head -n 50
