---
- name: ensure that services and timers are started and enabled
  become: true
  service:
    daemon_reload: true
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - openvpn@client.service
    - prometheus.service
    - snmp_exporter.service
    - prometheus-node-exporter.service
    - blackbox-exporter.service
    - grafana-server.service
    - influxdb.service
    - telegraf.service
    - textfile-job.service
    - textfile-job.timer
    - networkcheck.service
    - networkcheck.timer
    - vpncheck.service
    - fail2ban.service
