---
# Revoke openvpn client keys and all of its certs

- name: revoke certificates
  command: sh revoke.sh {{ item }}.crt
  args:
    chdir: "{{ openvpn_key_directory }}"
  with_items: '{{ openvpn_revoke_certs }}'

- name: remove client key
  file:
    path: "{{ openvpn_config_directory }}/easy-rsa/pki/private/{{ item }}.key"
    state: absent
    force: true
  with_items: '{{ openvpn_revoke_certs }}'

- name: remove client csr
  file:
    path: "{{ openvpn_key_directory }}/{{ item }}.csr"
    state: absent
    force: true
  with_items: '{{ openvpn_revoke_certs }}'

- name: remove client crt
  file:
    path: "{{ openvpn_config_directory }}/easy-rsa/pki/issued/{{ item }}.crt"
    state: absent
    force: true
  with_items: '{{ openvpn_revoke_certs }}'

- name: remove client cert only file
  file:
    path: "{{ openvpn_config_directory }}/easy-rsa/pki/issued/{{ item }}-crt-only.crt"
    state: absent
    force: true
  with_items: "{{ openvpn_clients }}"

- name: remove client config
  file:
    path: "{{ openvpn_ovpn_directory }}/{{ item }}.ovpn"
    state: absent
    force: true
  with_items: '{{ openvpn_revoke_certs }}'

- name: Check client config .ovpn name
  debug:
    msg: "{{ openvpn_ovpn_directory }}/{{ item }}.ovpn"
  with_items: '{{ openvpn_revoke_certs }}'
  when: openvpn_revoke_certs is defined
