---
# Define all handlers here

# - name: restart service
#   service:
#     name: influxdb.service
#     state: restarted
#   notify: restart memcached

# - name: restart memcached
#   service:
#     name: memcached
#     state: restarted

- name: restart ssh
  become: true
  systemd:
    name: sshd
    state: restarted

- name: restart openvpn
  become: true
  systemd:
    name: openvpn
    state: restarted

- name: reload prometheus
  become: true
  systemd:
    name: prometheus
    state: reloaded

- name: restart prometheus
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted