---
- name: reload snmp exporter
  service:
    daemon_reload: true
    name: snmp_exporter
    state: reloaded

- name: restart snmp exporter
  service:
    daemon_reload: true
    name: snmp_exporter
    state: restarted

- name: enable snmp exporter
  service:
    daemon_reload: true
    name: snmp_exporter
    enabled: true
