---
# Define grafana config here

- name: Create grafana system group
  group:
    name: grafana
    system: true
    state: present

- name: Create grafana system user
  user:
    name: grafana
    system: true
    shell: "/usr/sbin/nologin"
    group: grafana
    createhome: false

- name: Setup grafana environment
  template:
    src: grafana-server.env.j2
    dest: "{{ grafana_config_directory }}/grafana-server.env"
    owner: grafana
    group: grafana
    mode: 0640

# - name: Create grafana main configuration file
#   template:
#     src: grafana.ini.j2
#     dest: "{{ grafana_config_directory }}/conf/grafana.ini"
#     owner: grafana
#     group: grafana
#     mode: 0640

- name: Create grafana service file
  template:
    src: grafana-server.service.j2
    dest: "{{ grafana_service_file_directory }}/grafana-server.service"
    owner: grafana
    group: grafana
    mode: 0640

- name: Edit grafana ini file
  ini_file:
    path: "{{ grafana_config_directory }}/conf/grafana.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ grafana_ini }}"

- name: Change ownership of grafana directories
  file:
    path: "{{ grafana_config_directory }}"
    owner: grafana
    group: grafana
    mode: 0640

- name: Enable and start grafana systemd unit
  systemd:
    daemon_reload: true
    name: grafana-server
    enabled: true
    state: started
