---
# Ansible main playbook for cloud hosted servers

- hosts: server
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600

  vars_files:
    - vars/all.yml

    # - vars/init_local_vars.yml
    # - vars/prometheus_vars.yml
    # - vars/snmp_exporter_vars.yml
    # - vars/node_exporter_vars.yml
    # - vars/blackbox_exporter_vars.yml
    # - vars/grafana_vars.yml
    # - vars/openvpn_vars.yml
    # - vars/nginx_vars.yml

  handlers:

  roles:
    - roles/init-local
    - roles/openvpn-server-local
    - roles/grafana-server-local

  tasks:

    # Use Kickstart to setup a Linux client:
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/identity_management_guide/kickstart
    # https://help.ubuntu.com/lts/installation-guide/powerpc/ch04s05.html
    # https://help.ubuntu.com/community/KickstartCompatibility

    # Create users based on GitHub accounts and add all the pubkeys associated with the GitHub account
    # https://galaxy.ansible.com/geerlingguy/github-users

    # Install and configure certbot
    # ansible-galaxy install geerlingguy.certbot

