---
# https://github.com/cloudalchemy/ansible-prometheus

prometheus_binary_dir: /usr/local/bin
prometheus_config_dir: /usr/local/etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_listen_address: ":9020"
prometheus_web_external_url: ''

prometheus_storage_retention: "30d"

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_scrape_configs:

  - job_name: prometheus
    static_configs:
    - targets:
      - 10.8.0.2:9020
      - 192.168.0.50:9020

  - job_name: node
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.0.50:9011']
      - targets: ['localhost:9011']

  - job_name: Cisco
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 192.168.0.239  # SNMP Router Cisco.
        - 192.168.0.77  # SNMP Access Point Cisco.
    metrics_path: /snmp
    params:
      module: [Cisco]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 10.8.0.2:9030  # The SNMP exporter's real hostname:port.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://fypbcu.co.uk:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9092  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox-targets'
    metrics_path: /probe
    params:
      module:
        - dns_google
    static_configs:
      - targets:
         - "8.8.8.8"
         - "1.1.1.1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9092  # The blackbox exporter's real hostname:port.

  - job_name: 'http_ipv4'
    metrics_path: /probe
    params:
      module:
         - http_2xx_ipv4
    static_configs:
      - targets:
        - http://fypbcu.co.uk # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9092  # The blackbox exporter's real hostname:port.

  - job_name: 'ICMP'
    metrics_path: /probe
    params:
      module:
         - icmp
    static_configs:
      - targets:
        - 54.36.163.113
        - 82.153.171.48
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9092  # The blackbox exporter's real hostname:port.
