---
# Define prometheus node-exporter here

- name: Copy the node_exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: "{{ node_exporter_service_file_directory }}/prometheus-node-exporter.service"
    owner: prometheus
    group: prometheus
    mode: 0644
  notify: restart node_exporter

- name: Set node-exporter command-line options
  lineinfile:
    path: "{{ node_exporter_config_directory }}/node-exporter/prometheus-node-exporter"
    regexp: '^  --web.listen-address="{{ node_exporter_web_listen_address }}"'
    insertafter: '^ARGS='
    line: '  --web.listen-address="{{ node_exporter_web_listen_address }}"'

- name: Add execute permission to node_exporter binary
  file:
    path: "{{ node_exporter_binary_directroy }}/prometheus-node-exporter"
    mode: a+x

- name: Create textfile collector dir
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: true
    mode: u+rwX,g+rwX,o=rX
  when: node_exporter_textfile_dir | length > 0

# - name: Allow node_exporter port in SELinux on RedHat OS family
#   seport:
#     ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
#     proto: tcp
#     setype: http_port_t
#     state: present
#   when:
#     - ansible_version.full is version_compare('2.4', '>=')
#     - ansible_selinux.status == "enabled"

- name: Ensure prometheus-node-exporter is started and enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: prometheus-node-exporter
    enabled: true
    state: started
