---
# Generate and copy over an OpenVPN client.conf file to the node
# Write a custom role for OpenVPN server and client
# https://www.digitalocean.com/community/tutorials/how-to-set-up-and-configure-an-openvpn-server-on-ubuntu-20-04

# Deploy public key to remote hosts
# https://medium.com/@visualskyrim/ansible-playbook-deploy-the-public-key-to-remote-hosts-da3f3b4b5481
# https://www.youtube.com/watch?v=s8XVp3tdpas

# Define OpenVPN client configs here

- name: install openvpn
  apt:
    name: openvpn
    state: present

- name: transfer a generated ovpn file from the local machine to the node
  copy:
    src: "{{ openvpn_fetch_config_directory }}/{{ openvpn_server_hostname }}/{{ node_hostname }}.ovpn"
    dest: "{{ openvpn_config_directory }}/client.conf"

- name: enable openvpn autostart
  become: true
  lineinfile:
    path: /etc/default/openvpn
    regexp: '^AUTOSTART='
    line: 'AUTOSTART="all"'
  notify:
    - enable openvpn
    - start openvpn
